### ISSUE TITLE
Documentation Consistency & Format Options

### ISSUE THREAD

**Issue by AustinSaintAubin** [cncjs/cncjs.org#1]
We need to remove duplicate information.
The [website documentation](https://cnc.js.org/docs/) or the [wiki](https://github.com/cncjs/cncjs/wiki) needs to be one source for documentation.

We also have some options for building documentation with tools like [Sphinx](http://sphinx-doc.org) as used by [pip](https://pip.pypa.io/en/stable/quickstart).
Personally I think we need to go back to the wiki format... unless your goal is to include the help guides in the release. Then having all the documentation in the website is the best idea.

**In regard to wiki's there are some decent references:**

- [About GitHub Wikis](https://help.github.com/articles/about-github-wikis/)
- [Projects with great wikis](https://github.com/showcases/projects-with-great-wikis)

**Comment by cheton** [comment]
Sorry for the late. I should open this issue two weeks ago for discussions.

The website was generated using [Gatsby](https://github.com/gatsbyjs/gatsby) - a React.js static site generator. I built up an automation script that can automatically deploy page contents to the `gh-pages` branch. Each time you update any markdown files (e.g. index.md) in https://github.com/cncjs/cncjs.org/tree/master/pages/docs, it triggers a [Travis CI build](https://travis-ci.org/cncjs/cncjs.org) and publish the website.

For example, if you want to update [Raspberry Pi Setup Guide](https://github.com/cncjs/cncjs.org/blob/master/pages/docs/rpi-setup-guide/index.md), you can go to https://github.com/cncjs/cncjs.org/blob/master/pages/docs/rpi-setup-guide/index.md, and make changes just like you did on wiki pages. It may take about 20 minutes for GitHub to complete the cache invalidation for the website.

The purpose for creating this repo is to centralize all documentations in one single place. Wiki page is good, but it existed some limitations especially when interations or animations are needed, so I'd like to gradually move all contents from wiki page to here, and leave only <b>Table of Contents</b> to the Wiki's home page: https://github.com/cncjs/cncjs/wiki

If we decide to keep the same copy on the wiki page as well as the website, it's still doable using a script to clone wiki repo on each Travis CI build, and push changes when deployment. So we don't need to update them over two different places. See https://help.github.com/articles/adding-and-editing-wiki-pages-locally. 

This concept was inspired from https://github.com/webpack/webpack.js.org, I think it's worth it for maintaining both documentation and website.

**Comment by cheton** [comment]
Publish GitBook to Your GitHub Pages
http://sangsoonam.github.io/2016/08/02/publish-gitbook-to-your-github-pages.html

**Comment by cheton** [comment]
Wiki will be the source for documentation. I will create a script running on Travis CI to automatically sync the wiki content to the cncjs.org repository.
