### ISSUE TITLE
Error when attempting to install on Raspberry Pi using fully patched Raspberry Pi OS and latest Node.js

### ISSUE THREAD

**Issue by eat-sleep-code** [cncjs/cncjs.org#11]
The following error is thrown on a Raspberry Pi using a fully patched (as of October 24, 2020) version of Raspberry Pi OS.

> 
> > @serialport/bindings@2.0.8 install /home/pi/.npm-global/lib/node_modules/cncjs/node_modules/@serialport/bindings
> > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
> 
> prebuild-install WARN install No prebuilt binaries found (target=15.0.1 runtime=node arch=arm libc= platform=linux)
> make: Entering directory '/home/pi/.npm-global/lib/node_modules/cncjs/node_modules/@serialport/bindings/build'
>   CXX(target) Release/obj.target/bindings/src/serialport.o
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>    uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen);
>                                                                      ^~~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>  uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate);
>                                                                      ^~~~~~~~~~~~~~~
> 
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose);
>                                                                      ^~~~~~~~~~~~~~
> 
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush);
>                                                                      ^~~~~~~~~~~~~~
> 
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:270:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>    uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet);
>                                                                     ^~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:314:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>    uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet);
>                                                                     ^~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:
> ../src/serialport.cpp:329:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’
>  an::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
>                                                                               ^
> 
> In file included from /home/pi/.cache/node-gyp/15.0.1/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note:   candidate expects 3 arguments, 2 provided
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp:330:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’
>  an::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
>                                                                               ^
> 
> In file included from /home/pi/.cache/node-gyp/15.0.1/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note:   candidate expects 3 arguments, 2 provided
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp:331:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’
>  an::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
>                                                                               ^
> 
> In file included from /home/pi/.cache/node-gyp/15.0.1/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note:   candidate expects 3 arguments, 2 provided
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:363:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>  eue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate);
>                                                                      ^~~~~~~~~~~~~~~~~~~~
> 
> ../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:
> ../src/serialport.cpp:378:106: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’
>  ::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
>                                                                               ^
> 
> In file included from /home/pi/.cache/node-gyp/15.0.1/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3716:37: note:   candidate expects 3 arguments, 2 provided
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>                                      ^~~
> /home/pi/.cache/node-gyp/15.0.1/include/node/v8.h:3719:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:409:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);
>                                                                      ^~~~~~~~~~~~~~
> 
> ../src/serialport.cpp: At global scope:
> ../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses]
>  SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {
>                             ^
> ../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses]
>  SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {
>                               ^
> In file included from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/pi/.cache/node-gyp/15.0.1/include/node/node.h:842:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
>        (node::addon_register_func) (regfunc),                          \
>                                            ^
> /home/pi/.cache/node-gyp/15.0.1/include/node/node.h:876:3: note: in expansion of macro ‘NODE_MODULE_X’
>    NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
>    ^~~~~~~~~~~~~
> ../src/serialport.cpp:483:1: note: in expansion of macro ‘NODE_MODULE’
>  NODE_MODULE(serialport, init);
>  ^~~~~~~~~~~
> make: *** [bindings.target.mk:112: Release/obj.target/bindings/src/serialport.o] Error 1
> make: Leaving directory '/home/pi/.npm-global/lib/node_modules/cncjs/node_modules/@serialport/bindings/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
> gyp ERR! System Linux 5.4.51-v7l+
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/pi/.npm-global/lib/node_modules/cncjs/node_modules/@serialport/bindings
> gyp ERR! node -v v15.0.1
> gyp ERR! node-gyp -v v5.1.0
>

**Comment by MitchBradley** [comment]
The latest version of Node.JS will not work because CNCjs uses a version of the serialport module that is not compatible with recent versions of Node.

Use these instructions for a successful Pi installation https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-Install-Node.js-via-Package-Manager-*(Recommended)*
