### ISSUE TITLE
Error in CONTRIBUTING instructions

### ISSUE THREAD

**Issue by MitchBradley** [cncjs/cncjs.org#3]
CONTRIBUTING.md says (excerpted):

```
npm run build
npm dev
```

I don't think 'npm dev' is a valid command;  npm@5.4.2 doesn't understand it.  I had to start cnc with

`bin/cnc
`
I would also like to create a development build but I can't figure out how.  So many frameworks!

**Comment by cheton** [comment]
It's supposed to be `npm run dev`. I have updated the build instructions in the [CONTRIBUTING.md](https://github.com/cncjs/cncjs.org/blob/master/CONTRIBUTING.md) and [README.md](https://github.com/cncjs/cncjs.org/blob/master/README.md) files. Thank you.
